= Spring Data Sandbox

Sandbox project for experiments with https://spring.io/projects/spring-data[Spring Data]

== Goal

This sandbox helps to understand tricky moments of JPA, Hibernate and Spring Data JPA.

Unfortunately, most of the books and tutorials do not provide deep cover of ORM ecosystem.
Tests, which are presented in this project, allow tracing and debugging questions or issues that are interesting to me.

=== Disclaimer

* Tests do *not* cover all cases. I do not pursue the goal to provide "good" code coverage.
* I do not like the idea to use TestContainers and Spring Context for unit testing (both of them should be used for _integration tests_), however I use them here because it shows real JPA behaviour.

=== Some Covered Issues

* saving `java.time.Instant` field into PostgreSQL `timestamp`;
* emulate two transactions in tests to get Optimistic Lock issue;
* retry operation if some constrains are failed;
* use Optimistic Lock for aggregates (based on https://vladmihalcea.com/how-to-increment-the-parent-entity-version-whenever-a-child-entity-gets-modified-with-jpa-and-hibernate/[this] and https://techblog.bozho.net/spring-managed-hibernate-event-listeners/[this]);
* test type detection for inheritance entities;
