spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: db/changelog/changelog-master.xml
